/*
 *
 * SearchPage constants
 *
 */

export const DEFAULT_ACTION = 'app/SearchPage/DEFAULT_ACTION';

export const SEARCH_BUSINESS_EXPERTISE_BY_EXPERTISE_ID = 'app/SearchPage/SEARCH_BUSINESS_EXPERTISE_BY_EXPERTISE_ID';
export const LOAD_BUSINESS_EXPERTISE = 'bindeeFrontend/App/LOAD_BUSINESS_EXPERTISE';
export const LOAD_BUSINESS_EXPERTISE_SUCCESS = 'bindeeFrontend/App/LOAD_BUSINESS_EXPERTISE_SUCCESS';
export const LOAD_BUSINESS_EXPERTISE_ERROR = 'bindeeFrontend/App/LOAD_BUSINESS_EXPERTISE_ERROR';